// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, DeleteSandboxData, DeleteSandboxErrors, DeleteSandboxResponses, ExecCommandData, ExecCommandErrors, ExecCommandResponses, GetSandboxData, GetSandboxErrors, GetSandboxResponses, ListSandboxesData, ListSandboxesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Sandboxes
 *
 * List the sandboxes discoverable on the host.
 *
 * Enumerates host VM ids directly rather than the in-memory
 * registry, so sandboxes created before this server started are
 * included. Sandboxes that cannot be reconnected are omitted.
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(options?: Options<ListSandboxesData, ThrowOnError>): RequestResult<ListSandboxesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSandboxesResponses, unknown, ThrowOnError>({ url: '/sandboxes', ...options });

/**
 * Create Sandbox
 *
 * Create, boot, and register a new sandbox.
 *
 * Builds a :class:`~smolvm.SmolVM` from the request's auto-config
 * fields, starts it, stores it in the registry under its id, and
 * returns the client-safe view.
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>): RequestResult<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError> => (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
    url: '/sandboxes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Sandbox
 *
 * Stop the sandbox, release its resources, and forget it.
 *
 * Evicts the facade from the registry so its id stops resolving —
 * the write-through delete the registry-as-cache model needs.
 */
export const deleteSandbox = <ThrowOnError extends boolean = false>(options: Options<DeleteSandboxData, ThrowOnError>): RequestResult<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}', ...options });

/**
 * Get Sandbox
 *
 * Return the current state of a sandbox.
 *
 * On a registry miss the sandbox is reconnected from the host, so
 * only a sandbox that exists nowhere yields a 404.
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>): RequestResult<GetSandboxResponses, GetSandboxErrors, ThrowOnError> => (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}', ...options });

/**
 * Exec Command
 *
 * Run a command inside a sandbox and return its result.
 *
 * Resolves the sandbox (reconnecting on a registry miss), then runs
 * the command over the facade's cached SSH channel.
 */
export const execCommand = <ThrowOnError extends boolean = false>(options: Options<ExecCommandData, ThrowOnError>): RequestResult<ExecCommandResponses, ExecCommandErrors, ThrowOnError> => (options.client ?? client).post<ExecCommandResponses, ExecCommandErrors, ThrowOnError>({
    url: '/sandboxes/{sandbox_id}/exec',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
