// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, GetSandboxData, GetSandboxErrors, GetSandboxResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create Sandbox
 *
 * Create, boot, and register a new sandbox.
 *
 * Builds a :class:`~smolvm.SmolVM` from the request's auto-config
 * fields, starts it, stores it in the registry under its id, and
 * returns the client-safe view.
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>): RequestResult<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError> => (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
    url: '/sandboxes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Sandbox
 *
 * Return the current state of a sandbox.
 *
 * The in-memory registry is treated as a cache, not the source of
 * truth: on a miss we try to reconnect to a sandbox that exists on
 * the host (e.g. one created before this server process started)
 * via :meth:`SmolVM.from_id`, and backfill the registry so later
 * calls hit the fast path. Only a sandbox that exists nowhere on
 * the host yields a 404.
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>): RequestResult<GetSandboxResponses, GetSandboxErrors, ThrowOnError> => (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}', ...options });
