// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CreateSandboxRequest
 *
 * Request body for creating (and booting) a sandbox.
 *
 * Mirrors the auto-config arguments of the :class:`smolvm.SmolVM`
 * constructor. All fields are optional; omitting them boots the
 * default Alpine micro-VM.
 */
export type CreateSandboxRequest = {
    /**
     * Image
     *
     * Image reference to boot (S3 ref, file:// URI, or path). Omit to use the default built-in image.
     */
    image?: string | null;
    /**
     * Os
     *
     * Guest OS for auto-configured images: 'alpine', 'ubuntu', or 'windows'.
     */
    os?: 'alpine' | 'ubuntu' | 'windows' | null;
    /**
     * Memory
     *
     * Guest memory in MiB.
     */
    memory?: number | null;
    /**
     * Disk Size
     *
     * Guest disk size in MiB.
     */
    disk_size?: number | null;
    /**
     * Backend
     *
     * Runtime backend override: 'firecracker', 'qemu', or 'libkrun'.
     */
    backend?: 'firecracker' | 'qemu' | 'libkrun' | null;
};

/**
 * ErrorResponse
 *
 * The body returned for a handled 4xx error.
 *
 * Mirrors FastAPI's :class:`~fastapi.HTTPException` shape (``{detail}``)
 * so the generated SDKs get a typed error surface distinct from the
 * 422 request-validation body, whose ``detail`` is a list of field
 * errors rather than a single string.
 */
export type ErrorResponse = {
    /**
     * Detail
     *
     * Human-readable explanation of the error.
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SandboxResponse
 *
 * A sandbox's public, client-safe state.
 *
 * Host-internal details (disk paths, PID, network device) are
 * intentionally omitted — clients address a sandbox only by ``id``.
 */
export type SandboxResponse = {
    /**
     * Id
     *
     * Stable sandbox identifier.
     */
    id: string;
    /**
     * Current lifecycle state.
     */
    status: VmState;
};

/**
 * VMState
 *
 * VM lifecycle states.
 */
export type VmState = 'created' | 'running' | 'paused' | 'stopped' | 'error';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateSandboxData = {
    body: CreateSandboxRequest;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * The request was invalid or the sandbox failed to boot.
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Successful Response
     */
    201: SandboxResponse;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type GetSandboxErrors = {
    /**
     * No sandbox with that id exists on the host.
     */
    404: ErrorResponse;
    /**
     * The sandbox exists but could not be reconnected.
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Successful Response
     */
    200: SandboxResponse;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];
