// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CreateSandboxRequest
 *
 * Request body for creating (and booting) a sandbox.
 *
 * Mirrors the auto-config arguments of the :class:`smolvm.SmolVM`
 * constructor. All fields are optional; omitting them boots the
 * default Alpine micro-VM.
 */
export type CreateSandboxRequest = {
    /**
     * Image
     *
     * Image reference to boot (S3 ref, file:// URI, or path). Omit to use the default built-in image.
     */
    image?: string | null;
    /**
     * Os
     *
     * Guest OS for auto-configured images: 'alpine', 'ubuntu', or 'windows'.
     */
    os?: 'alpine' | 'ubuntu' | 'windows' | null;
    /**
     * Memory
     *
     * Guest memory in MiB.
     */
    memory?: number | null;
    /**
     * Disk Size
     *
     * Guest disk size in MiB.
     */
    disk_size?: number | null;
    /**
     * Backend
     *
     * Runtime backend override: 'firecracker', 'qemu', or 'libkrun'.
     */
    backend?: 'firecracker' | 'qemu' | 'libkrun' | null;
};

/**
 * ErrorResponse
 *
 * The body returned for a handled 4xx error.
 *
 * Mirrors FastAPI's :class:`~fastapi.HTTPException` shape (``{detail}``)
 * so the generated SDKs get a typed error surface distinct from the
 * 422 request-validation body, whose ``detail`` is a list of field
 * errors rather than a single string.
 */
export type ErrorResponse = {
    /**
     * Detail
     *
     * Human-readable explanation of the error.
     */
    detail: string;
};

/**
 * ExecRequest
 *
 * Request body for running a command inside a sandbox.
 *
 * Mirrors the arguments of :meth:`smolvm.SmolVM.run`.
 */
export type ExecRequest = {
    /**
     * Command
     *
     * Shell command to execute in the sandbox.
     */
    command: string;
    /**
     * Timeout
     *
     * Maximum seconds to wait for the command to finish.
     */
    timeout?: number;
    /**
     * Shell
     *
     * 'login' runs via the guest login shell; 'raw' executes the command directly with no shell wrapping.
     */
    shell?: 'login' | 'raw';
};

/**
 * ExecResponse
 *
 * The result of a command run inside a sandbox.
 *
 * Reuses the engine's :class:`~smolvm.types.CommandResult` (exit code,
 * stdout, stderr) under an API-owned name so the generated SDKs expose
 * a stable ``ExecResponse`` type rather than an engine-internal one.
 */
export type ExecResponse = {
    /**
     * Exit Code
     */
    exit_code: number;
    /**
     * Stdout
     */
    stdout: string;
    /**
     * Stderr
     */
    stderr: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SandboxResponse
 *
 * A sandbox's public, client-safe state.
 *
 * Host-internal details (disk paths, PID, network device) are
 * intentionally omitted — clients address a sandbox only by ``id``.
 */
export type SandboxResponse = {
    /**
     * Id
     *
     * Stable sandbox identifier.
     */
    id: string;
    /**
     * Current lifecycle state.
     */
    status: VmState;
};

/**
 * VMState
 *
 * VM lifecycle states.
 */
export type VmState = 'created' | 'running' | 'paused' | 'stopped' | 'error';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type ListSandboxesResponses = {
    /**
     * Response Listsandboxes
     *
     * Successful Response
     */
    200: Array<SandboxResponse>;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: CreateSandboxRequest;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * The request was invalid or the sandbox failed to boot.
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Successful Response
     */
    201: SandboxResponse;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type DeleteSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type DeleteSandboxErrors = {
    /**
     * No sandbox with that id exists on the host.
     */
    404: ErrorResponse;
    /**
     * The sandbox could not be reconnected or deleted.
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSandboxError = DeleteSandboxErrors[keyof DeleteSandboxErrors];

export type DeleteSandboxResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSandboxResponse = DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type GetSandboxErrors = {
    /**
     * No sandbox with that id exists on the host.
     */
    404: ErrorResponse;
    /**
     * The sandbox exists but could not be reconnected.
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Successful Response
     */
    200: SandboxResponse;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type ExecCommandData = {
    body: ExecRequest;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/exec';
};

export type ExecCommandErrors = {
    /**
     * No sandbox with that id exists on the host.
     */
    404: ErrorResponse;
    /**
     * The sandbox could not be reconnected, or the command could not run.
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecCommandError = ExecCommandErrors[keyof ExecCommandErrors];

export type ExecCommandResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecCommandResponse = ExecCommandResponses[keyof ExecCommandResponses];
